# Generated by Django 5.2.9 on 2026-01-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uchrashuv_sanasi', models.DateTimeField(verbose_name='Uchrashuv sanasi')),
                ('rejalashtirilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Rejalashtirilgan sana')),
                ('shifokor', models.CharField(max_length=200, verbose_name='Shifokor')),
                ('bolim', models.CharField(choices=[('terapiya', 'Terapiya'), ('kardiologiya', 'Kardiologiya'), ('endokrinologiya', 'Endokrinologiya'), ('nevrologiya', 'Nevrologiya'), ('pediatriya', 'Pediatriya'), ('ginekologiya', 'Ginekologiya'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Bölim')),
                ('sms_yuborildi', models.BooleanField(default=False, verbose_name='SMS yuborildi')),
                ('kelmay_qolish_riski', models.FloatField(blank=True, null=True, verbose_name='Kelmay qolish riski')),
                ('qand_riski', models.FloatField(blank=True, null=True, verbose_name='Qand riski')),
                ('yurak_riski', models.FloatField(blank=True, null=True, verbose_name='Yurak riski')),
                ('holat', models.CharField(choices=[('rejalashtirilgan', 'Rejalashtirilgan'), ('yakunlangan', 'Yakunlangan'), ('bekor_qilingan', 'Bekor qilingan'), ('kelmagan', 'Kelmagan')], default='rejalashtirilgan', max_length=50, verbose_name='Holat')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Uchrashuv',
                'verbose_name_plural': 'Uchrashuvlar',
                'ordering': ['-uchrashuv_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200, verbose_name='Ism')),
                ('yosh', models.IntegerField(verbose_name='Yosh')),
                ('jins', models.CharField(choices=[('E', 'Erkak'), ('A', 'Ayol')], max_length=1, verbose_name='Jins')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('manzil', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('qon_guruhi', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Qon guruhi')),
                ('allergiyalar', models.TextField(blank=True, null=True, verbose_name='Allergiyalar')),
                ('qand_kasalligi', models.BooleanField(default=False, verbose_name='Qand kasalligi')),
                ('gipertoniya', models.BooleanField(default=False, verbose_name='Gipertoniya')),
                ('yurak_kasalligi', models.BooleanField(default=False, verbose_name='Yurak kasalligi')),
                ('umumiy_uchrashuvlar', models.IntegerField(default=0, verbose_name='Umumiy uchrashuvlar')),
                ('kelmaganlar_soni', models.IntegerField(default=0, verbose_name='Kelmaganlar soni')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='HealthScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qon_bosimi_yuqori', models.IntegerField(blank=True, null=True, verbose_name='Qon bosimi (yuqori)')),
                ('qon_bosimi_past', models.IntegerField(blank=True, null=True, verbose_name='Qon bosimi (past)')),
                ('puls', models.IntegerField(blank=True, null=True, verbose_name='Puls')),
                ('harorat', models.FloatField(blank=True, null=True, verbose_name='Harorat')),
                ('glyukoza', models.FloatField(blank=True, null=True, verbose_name='Glyukoza (mg/dL)')),
                ('holesterin', models.FloatField(blank=True, null=True, verbose_name='Holesterin')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('qand_ehtimoli', models.FloatField(blank=True, null=True, verbose_name='Qand ehtimoli')),
                ('yurak_ehtimoli', models.FloatField(blank=True, null=True, verbose_name='Yurak ehtimoli')),
                ('tekshirilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Tekshirilgan sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Shifokor izohi')),
                ('uchrashuv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekshiruvlar', to='patients.appointment', verbose_name='Uchrashuv')),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tekshiruvlar', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': "Sog'liqni tekshirish",
                'verbose_name_plural': "Sog'liqni tekshirishlar",
                'ordering': ['-tekshirilgan_sana'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='bemor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uchrashuvlar', to='patients.patient', verbose_name='Bemor'),
        ),
    ]
