# Generated by Django 5.2.10 on 2026-01-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('diabetes', 'Qand kasalligi (Diabetes)'), ('heart', 'Yurak kasalligi (Heart Disease)')], max_length=20, verbose_name='Protokol turi')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('shifokor', models.CharField(blank=True, max_length=200, verbose_name='Shifokor')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('transcript', models.TextField(blank=True, verbose_name='Ovozli yozuv matni')),
                ('qon_guruhi', models.CharField(blank=True, choices=[('O(I)', 'O(I)'), ('A(II)', 'A(II)'), ('B(III)', 'B(III)'), ('AB(IV)', 'AB(IV)')], max_length=10, null=True, verbose_name='Qon guruhi')),
                ('allergiyalar', models.TextField(blank=True, null=True, verbose_name='Allergiyalar')),
                ('qand_kasalligi', models.BooleanField(default=False, verbose_name='Qand kasalligi mavjud')),
                ('gipertoniya', models.BooleanField(default=False, verbose_name='Gipertoniya mavjud')),
                ('yurak_kasalligi', models.BooleanField(default=False, verbose_name='Yurak kasalligi mavjud')),
                ('pregnancies', models.IntegerField(blank=True, help_text='0-17 orasida', null=True, verbose_name='Homiladorlik soni')),
                ('glucose', models.FloatField(blank=True, help_text='0-200 orasida', null=True, verbose_name='Glyukoza darajasi (mg/dL)')),
                ('blood_pressure', models.IntegerField(blank=True, help_text='0-130 orasida', null=True, verbose_name='Qon bosimi (mm Hg)')),
                ('skin_thickness', models.IntegerField(blank=True, help_text='0-99 orasida', null=True, verbose_name='Teri qalinligi (mm)')),
                ('insulin', models.FloatField(blank=True, help_text='0-850 orasida', null=True, verbose_name='Insulin darajasi (mu U/ml)')),
                ('bmi', models.FloatField(blank=True, help_text='0-70 orasida', null=True, verbose_name='BMI (Tana massasi indeksi)')),
                ('diabetes_pedigree', models.FloatField(blank=True, help_text='0.0-2.5 orasida', null=True, verbose_name='Irsiy omil koeffitsienti')),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Erkak'), (0, 'Ayol')], null=True, verbose_name='Jins (model uchun)')),
                ('chest_pain_type', models.IntegerField(blank=True, choices=[(0, 'Asimptomatik'), (1, 'Atipik angina'), (2, "Angina bo'lmagan og'riq"), (3, 'Tipik angina')], null=True, verbose_name="Ko'krak og'rig'i turi")),
                ('resting_bp', models.IntegerField(blank=True, help_text='90-200 orasida', null=True, verbose_name='Dam olishdagi qon bosimi (mm Hg)')),
                ('cholesterol', models.FloatField(blank=True, help_text='100-600 orasida', null=True, verbose_name='Xolesterin (mg/dl)')),
                ('fasting_blood_sugar', models.BooleanField(blank=True, null=True, verbose_name='Och qorindagi qand > 120 mg/dl')),
                ('rest_ecg', models.IntegerField(blank=True, help_text='0=Normal, 1=ST-T anormalligi, 2=Chap qorincha gipertrofiyasi', null=True, verbose_name='Dam olishdagi EKG natijasi')),
                ('max_heart_rate', models.IntegerField(blank=True, help_text='70-210 orasida', null=True, verbose_name='Maksimal yurak urishi')),
                ('exercise_angina', models.BooleanField(blank=True, null=True, verbose_name='Jismoniy mashqda angina')),
                ('oldpeak', models.FloatField(blank=True, help_text='0.0-6.5 orasida', null=True, verbose_name='ST depressiyasi')),
                ('slope', models.IntegerField(blank=True, help_text='0=Pastga, 1=Tekis, 2=Yuqoriga', null=True, verbose_name='ST segment qiyaligi')),
                ('num_vessels', models.IntegerField(blank=True, help_text='Fluoroskopiyada ranglangan', null=True, verbose_name='Asosiy tomirlar soni (0-3)')),
                ('thal', models.IntegerField(blank=True, help_text='1=Normal, 2=Tuzatilgan nuqson, 3=Qaytmas nuqson', null=True, verbose_name='Talassemiya')),
                ('ai_prediction', models.FloatField(blank=True, null=True, verbose_name='AI bashorat natijasi (%)')),
                ('risk_level', models.CharField(blank=True, max_length=20, verbose_name='Xavf darajasi')),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokollar', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Protokol',
                'verbose_name_plural': 'Protokollar',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
    ]
