# Generated by Django 6.0.1 on 2026-01-21 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200, verbose_name='Ism')),
                ('lavozim', models.CharField(choices=[('doctor', 'Shifokor'), ('nurse', 'Hamshira'), ('admin', 'Administrator')], max_length=20, verbose_name='Lavozim')),
                ('bolim', models.CharField(choices=[('terapiya', 'Terapiya'), ('kardiologiya', 'Kardiologiya'), ('endokrinologiya', 'Endokrinologiya'), ('nevrologiya', 'Nevrologiya'), ('pediatriya', 'Pediatriya'), ('ginekologiya', 'Ginekologiya'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Bo‘lim')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('ishga_olingan_sana', models.DateField(default=django.utils.timezone.now, verbose_name='Ishga olingan sana')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['ism'],
            },
        ),
    ]
